#ifndef menuall2
#define menuall2
#include "dbf.hpp"
#include "mouse.hpp"
#include "button.hpp"
#include "drawrazd.hpp"
#include "menuall.hpp"
#include "globalda.hpp"
#include "textpack.hpp"
#include "set.hpp"
#include "bigpath.hpp"

void fragment(void);
void all(void);
void centr(void);
void rasst(void);
void slide(void);
void find_rg(void);
void find_punct(void);
void onoff(void);
void chmark(void);
void whatisitd(int mode);
void finddbf(void);
void xycoord(void);
void polygon(int);
void clearm(int);

#endif