.silent

PROJECT_NAME=dbf
ROOT_DIR=..\..

!include $(ROOT_DIR)\common\make_lib.inc

PUBLISHED_HEADERS=\
  $(PH:name=parse.h)\
  $(PH:name=u4error.h)\
  $(PH:name=base.hpp)\
  $(PH:name=convert.hpp)\
  $(PH:name=dbf.hpp)

!include $(ROOT_DIR)\common\publish.inc

