.silent

PROJECT_NAME=graphics
ROOT_DIR=..\..

!include $(ROOT_DIR)\common\make_lib.inc

PUBLISHED_HEADERS=\
  $(PH:name=graphics.h)\
  $(PH:name=drawpl.hpp)

!include $(ROOT_DIR)\common\publish.inc

